### ISSUE TITLE
Content Ownership Ambiguity! (Logo)

### ISSUE THREAD

**Issue by iamvee** [psycho-ir/mr-hashemi#2]
According to [Terms of Services](https://help.github.com/en/github/site-policy/github-terms-of-service), Section A: Defenitions, part 7: 

> “Content” refers to content featured or displayed through the Website, including without limitation code, text, data, articles, images, photographs, graphics, software, applications, packages, designs, features, and other materials that are available on the Website or otherwise available through the Service. "Content" also includes Services. “User-Generated Content” is Content, written or otherwise, created or uploaded by our Users. **"Your Content" is Content that you create or own.**

By that way, there's more on this topic on section **D. User-Generated Content**, third part, first paragraph : 

> **3. Ownership of Content, Right to Post, and License Grants**
You retain ownership of and responsibility for Your Content. If you're posting anything you did not create yourself or do not own the rights to, **you agree that you are responsible for any Content you post; ** that you will **ONLY** submit Content that **you have the right to post**; and that you will fully comply with any third party licenses relating to Content you post.

In bried, I guess there might be some kind of legal issues w/ this `Mr. Hashemi` logo and stuff.

**Comment by psycho-ir** [comment]
The current Mr. Hashemi's programming logo is about 25 years old and I don't think this photo even had copy right at those days (and if had it's still valid!). 
We will design a proper logo very soon though. 
Let me know if you have any idea about its look and feel :)
